using System;
using System.Collections;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Linq;
using System.Reflection.Emit;
using System.Threading.Tasks;
using ProjectEuler;

namespace Challenges
{
    public class Challenge2 : IRunChallenge
    {
        /// <summary>
        /// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
        /// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
        /// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
        /// </summary>
        public int MaxFibbValue { get; set; }   
        public int RunChallenge()
        {
            FibonacciSequence fibonacci = new FibonacciSequence();
            var evensum = fibonacci.TakeWhile(number => number < MaxFibbValue).Sum(Predicate);

            return evensum;
        }

        private int Predicate(int x)
        {
            if (x % 2 == 0)
            {
                return x;
            }

            return 0;
        }
    }
}
